
CREATE TABLE cliente(RFC_Cliente VARCHAR(100) PRIMARY KEY, Nombre VARCHAR(40) NOT NULL, Apellido1 VARCHAR(40) NOT NULL, Apellido2 VARCHAR(40), Nombre_Empresa VARCHAR(100), Direccion VARCHAR(200), Ciudad VARCHAR(50), Estado VARCHAR(50), CP CHAR(5))ENGINE=INNODB;

CREATE TABLE factura(Num_Factura INT(11) PRIMARY KEY, Fecha_Factura DATE, RFC_Cliente VARCHAR(100))ENGINE=INNODB;

CREATE TABLE detallefactura(Num_DetalleFactura INT(11) PRIMARY KEY, Num_Factura INT(11), Cod_Articulo INT(11), Cantidad INT(11))ENGINE=INNODB;

CREATE TABLE proveedor(RFC_Proveedor VARCHAR(100) PRIMARY KEY, Nombre VARCHAR(40) NOT NULL, Apellido1 VARCHAR(40) NOT NULL, Apellido2 VARCHAR(40), Nombre_Empresa VARCHAR(100), Direccion VARCHAR(200), Ciudad VARCHAR(50), Estado VARCHAR(50), CP CHAR(5))ENGINE=INNODB;

CREATE TABLE articulo(Cod_Articulo INT(11) PRIMARY KEY, RFC_Proveedor VARCHAR(100), Nombre_Articulo VARCHAR(100) NOT NULL, Caracteristicas VARCHAR(200), Precio FLOAT NOT NULL)ENGINE=INNODB;
